services:
  web-api:
    build:
      context: ./backend
    image: smartx-storage-forecast-web-api:local
    env_file:
      - .env
    environment:
      SMARTX_PROJECT_PATH: /opt/smartx-storage-forecast
      SMARTX_COMPOSE_PROJECT_NAME: smartx-storage-forecast
      SMARTX_APP_VERSION: "0.3.2"
    volumes:
      - /data/smartx-capacity-insight-data/app:/data
      - /data/smartx-capacity-insight-data/prometheus:/prometheus-data
      - .:/opt/smartx-storage-forecast:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
    networks:
      - smartx-net
    restart: unless-stopped

  collector-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    image: smartx-storage-forecast-collector-worker:local
    command: ["python", "-m", "app.collector.worker"]
    env_file:
      - .env
    environment:
      SMARTX_APP_VERSION: "0.3.2"
    volumes:
      - /data/smartx-capacity-insight-data/app:/data
    expose:
      - "9108"
    depends_on:
      - prometheus
    networks:
      - smartx-net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    image: smartx-storage-forecast-frontend:local
    ports:
      - "8080:80"
    depends_on:
      - web-api
    networks:
      - smartx-net
    restart: unless-stopped

  upgrade-runner:
    build:
      context: ./backend
      dockerfile: Dockerfile.upgrade
    image: smartx-storage-forecast-upgrade-runner:local
    command: ["python", "-m", "app.upgrade.runner"]
    env_file:
      - .env
    environment:
      SMARTX_PROJECT_PATH: /opt/smartx-storage-forecast
      SMARTX_COMPOSE_PROJECT_NAME: smartx-storage-forecast
      SMARTX_APP_VERSION: "0.3.2"
    volumes:
      - .:/opt/smartx-storage-forecast
      - /data/smartx-capacity-insight-data/app:/data
      - /data/smartx-capacity-insight-data/prometheus:/prometheus-data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - prometheus
    networks:
      - smartx-net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.55.1
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=400d"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /data/smartx-capacity-insight-data/prometheus:/prometheus
    ports:
      - "9090:9090"
    networks:
      - smartx-net
    restart: unless-stopped


networks:
  smartx-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.249.249.0/24
