services:
  web-api:
    image: smartx-storage-forecast-web-api:0.4.0
    environment:
      SMARTX_APP_VERSION: "0.4.0"
  collector-worker:
    image: smartx-storage-forecast-collector-worker:0.4.0
    environment:
      SMARTX_APP_VERSION: "0.4.0"
  frontend:
    image: smartx-storage-forecast-frontend:0.4.0
