FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY VERSION ./VERSION
COPY backend/requirements*.txt .
RUN pip install --no-cache-dir -r requirements-worker.txt

COPY backend/app ./app

EXPOSE 9108

CMD ["python", "-m", "app.collector.worker"]
